import type { Catalog } from "./types";
export const contact = {
  whatsappDisplay: "+92 300 8548956",
  whatsapp: "923008548956",
  email: "cretechem@gmail.com",
  phones: ["+92 51-2808395", "+92 51-2808409"],
  address: "Block # 9, I & T Center, Street # 54, G-9/4, Islamabad, Pakistan",
};
export const cities = [
  "Islamabad",
  "Rawalpindi",
  "Lahore",
  "Karachi",
  "Peshawar",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Abbottabad",
];
export const seed: Catalog = {
  products: [
    {
      id: "membranes",
      name: "Membranes",
      category: "Membranes",
      applications: ["Roofs", "Basements", "Waterproofing details"],
      benefits: [
        "Bituminous and synthetic options",
        "Continuous waterproofing protection",
        "System selection and application guidance",
      ],
      description:
        "Bituminous & synthetic membranes for ultimate waterproofing.",
      image: "/assets/products/membranes.svg",
      imageUrl: "",
      label: "Featured",
      featured: true,
      active: true,
      serviceIds: [
        "roof-waterproofing",
        "bathroom-leakage",
        "basement-seepage",
        "heat-proofing",
      ],
    },
    {
      id: "coatings",
      name: "Coatings",
      category: "Coatings",
      applications: ["Concrete surfaces", "Walls", "Protective finishes"],
      benefits: [
        "Protective and decorative options",
        "Surface protection",
        "Application guidance",
      ],
      description: "Protective & decorative coatings for every surface.",
      image: "/assets/products/coatings.svg",
      imageUrl: "",
      label: "",
      featured: false,
      active: true,
      serviceIds: [
        "roof-waterproofing",
        "water-tank-leakage",
        "bathroom-leakage",
        "basement-seepage",
        "wall-dampness",
        "heat-proofing",
      ],
    },
    {
      id: "sealants",
      name: "Sealants",
      category: "Sealants",
      applications: [
        "Movement joints",
        "Construction joints",
        "Gaps and penetrations",
      ],
      benefits: [
        "Joint sealing",
        "Detail-friendly application",
        "Compatible system selection",
      ],
      description: "High-performance sealants for joints & gaps.",
      image: "/assets/products/sealants.svg",
      imageUrl: "",
      label: "",
      featured: false,
      active: true,
      serviceIds: [
        "roof-waterproofing",
        "water-tank-leakage",
        "bathroom-leakage",
        "wall-dampness",
      ],
    },
    {
      id: "grouts",
      name: "Grouts",
      category: "Grouts",
      applications: [
        "Base plates",
        "Equipment foundations",
        "Anchoring details",
      ],
      benefits: [
        "Precision placement",
        "Strength and durability",
        "Technical specification support",
      ],
      description: "Precision grouts for strength and durability.",
      image: "/assets/products/grouts.svg",
      imageUrl: "",
      label: "",
      featured: false,
      active: true,
      serviceIds: [],
    },
    {
      id: "admixtures",
      name: "Admixtures",
      category: "Admixtures",
      applications: [
        "Concrete mixes",
        "Site concrete",
        "Specified concrete applications",
      ],
      benefits: [
        "Concrete performance enhancement",
        "Mix-specific selection",
        "Technical dosage guidance",
      ],
      description: "Concrete admixtures for performance enhancement.",
      image: "/assets/products/admixtures.svg",
      imageUrl: "",
      label: "",
      featured: false,
      active: true,
      serviceIds: [],
    },
    {
      id: "repair-solutions",
      name: "Repair Solutions",
      category: "Repair Solutions",
      applications: [
        "Damaged concrete",
        "Spalled surfaces",
        "Rehabilitation works",
      ],
      benefits: [
        "Concrete repair and protection",
        "Substrate-specific selection",
        "Professional application support",
      ],
      description: "Concrete repair & protection for long lasting results.",
      image: "/assets/products/repair-solutions.svg",
      imageUrl: "",
      label: "",
      featured: false,
      active: true,
      serviceIds: ["water-tank-leakage", "basement-seepage", "wall-dampness"],
    },
  ],
  services: [
    {
      id: "roof-waterproofing",
      title: "Roof Waterproofing",
      description: "Protect your roof from leakage and harsh weather.",
      icon: "roof",
      tags: ["Roof Waterproofing", "leakage", "roof"],
      recommendedProductIds: ["membranes", "coatings", "sealants"],
      active: true,
    },
    {
      id: "water-tank-leakage",
      title: "Water Tank Leakage",
      description: "Long-lasting solutions for water tanks and reservoirs.",
      icon: "tank",
      tags: ["Water Tank Leakage"],
      recommendedProductIds: ["coatings", "sealants", "repair-solutions"],
      active: true,
    },
    {
      id: "bathroom-leakage",
      title: "Bathroom Leakage",
      description: "Stop seepage and protect your bathrooms permanently.",
      icon: "bath",
      tags: ["Bathroom Leakage"],
      recommendedProductIds: ["membranes", "coatings", "sealants"],
      active: true,
    },
    {
      id: "basement-seepage",
      title: "Basement Seepage",
      description: "Advanced systems to keep basements dry and strong.",
      icon: "basement",
      tags: ["Basement Seepage", "basement", "seepage"],
      recommendedProductIds: ["membranes", "coatings", "repair-solutions"],
      active: true,
    },
    {
      id: "wall-dampness",
      title: "Wall Dampness",
      description: "Eliminate rising damp and protect wall finishes.",
      icon: "wall",
      tags: ["Wall Dampness", "dampness", "wall"],
      recommendedProductIds: ["coatings", "sealants", "repair-solutions"],
      active: true,
    },
    {
      id: "heat-proofing",
      title: "Heat Proofing",
      description: "Reduce heat transfer and improve indoor comfort.",
      icon: "heat",
      tags: ["Heat Proofing"],
      recommendedProductIds: ["coatings", "membranes"],
      active: true,
    },
  ],
  banners: [
    {
      id: "free-inspection",
      title: "Start with a free site inspection",
      description: "Find the right solution for your structure.",
      link: "#contact",
      active: true,
    },
  ],
  cases: [
    {
      id: "roof",
      title: "Roof waterproofing",
      description:
        "Substrate crack injection, ponding elimination, and multi-layer elastomeric waterproofing membrane application.",
      beforeImage: "/assets/roof-before.webp",
      afterImage: "/assets/roof-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "concrete",
      title: "Concrete protection",
      description:
        "Polymer-modified structural repair mortars and anti-carbonation hydrophobic protective coatings.",
      beforeImage: "/assets/concrete-before.webp",
      afterImage: "/assets/concrete-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "basement",
      title: "Basement protection",
      description:
        "Negative-side crystalline slurry and high-pressure polyurethane chemical injection stopping groundwater seepage.",
      beforeImage: "/assets/basement-before.webp",
      afterImage: "/assets/basement-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "floor",
      title: "Industrial floor",
      description:
        "Heavy-duty self-leveling epoxy and polyurethane screed systems built for abrasion and chemical resistance.",
      beforeImage: "/assets/floor-before.webp",
      afterImage: "/assets/floor-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "bathroom",
      title: "Bathroom / Washroom",
      description:
        "Flexible two-component cementitious waterproofing around plumbing traps, sanitary fittings, and shower stalls.",
      beforeImage: "/assets/bathroom-before.webp",
      afterImage: "/assets/bathroom-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "wall",
      title: "Wall dampness",
      description:
        "Damp-proof chemical injection barriers and breathable anti-efflorescence protective coatings halting rising damp.",
      beforeImage: "/assets/wall-before.webp",
      afterImage: "/assets/wall-after.webp",
      active: true,
      illustrative: true,
    },
    {
      id: "tank",
      title: "Water tank",
      description:
        "Food-grade certified, non-toxic elastomeric waterproofing systems for underground and overhead reinforced concrete water tanks.",
      beforeImage: "/assets/tank-before.webp",
      afterImage: "/assets/tank-after.webp",
      active: true,
      illustrative: true,
    },
  ],
};
