const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses=['New','Contacted','Confirmed','In progress','Completed','Cancelled'];
let orders=[],nextOffset=null;
async function request(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await res.json();}catch{throw new Error('The admin service is temporarily unavailable. Please try again shortly.');}if(!res.ok){if(res.status===401){$('#login').hidden=false;$('#dashboard').hidden=true;orders=[];$('#orders').innerHTML='';}throw new Error(data.error||'Request failed.');}return data;}
function render(){
 const term=$('#search').value.toLowerCase(),status=$('#filter').value;
 const filtered=orders.filter(o=>(!status||o.status===status)&&`${o.id} ${o.customer.name} ${o.customer.phone} ${o.customer.address} ${o.items.map(i=>i.name).join(' ')}`.toLowerCase().includes(term));
 $('#order-count').textContent=`Showing ${filtered.length} of ${orders.length} loaded orders.`;
 $('#orders').innerHTML=filtered.length?filtered.map(o=>`<article class="order-card"><div class="order-title"><div><h2>${escape(o.customer.name)}</h2><div class="order-meta">${escape(o.id)}<br>${escape(new Date(o.createdAt).toLocaleString())}</div></div><span class="status-label">${escape(o.status)}</span></div><p class="order-meta">Phone: ${escape(o.customer.phone)}<br>Address / project location: ${escape(o.customer.address)}${o.customer.notes?`<br>Notes: ${escape(o.customer.notes)}`:''}</p><ul class="order-lines">${o.items.map(i=>`<li>${i.quantity} × ${escape(i.name)}</li>`).join('')}</ul><p class="quote-note">Quotation required · WhatsApp delivery unverified</p><div class="admin-actions"><label>Status <select class="admin-select" data-order="${o.id}" aria-label="Status for ${escape(o.customer.name)}">${statuses.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><a class="text-link" href="tel:${escape(o.customer.phone.replace(/[^+0-9]/g,''))}">Call customer ↗</a></div></article>`).join(''):'<div class="order-card"><h2>No orders to display</h2><p>New storefront orders will appear here. Try refreshing or changing your filters.</p></div>';
 $('#more').hidden=nextOffset===null;
}
async function load(append=false){$('#dashboard-error').textContent='';try{const data=await request(`/api/admin/orders?offset=${append?nextOffset:0}`);orders=append?[...orders,...data.orders]:data.orders;nextOffset=data.nextOffset;$('#total').textContent=data.stats.total;$('#new').textContent=data.stats.newOrders||0;$('#completed').textContent=data.stats.completed||0;$('#login').hidden=true;$('#dashboard').hidden=false;render();}catch(err){$('#dashboard-error').textContent=err.message;throw err;}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;$('#login-error').textContent='';try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:new FormData(e.currentTarget).get('password')})});e.target.reset();await load();}catch(err){$('#login-error').textContent=err.message;}finally{button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await request('/api/admin/logout',{method:'POST',body:'{}'});orders=[];$('#orders').innerHTML='';$('#dashboard').hidden=true;$('#login').hidden=false;}catch(err){$('#dashboard-error').textContent=err.message;}});
$('#refresh').addEventListener('click',()=>load().catch(()=>{}));$('#more').addEventListener('click',async e=>{e.target.disabled=true;try{await load(true);}catch{}finally{e.target.disabled=false;}});
$('#search').addEventListener('input',render);$('#filter').addEventListener('change',render);
$('#orders').addEventListener('change',async e=>{if(!e.target.dataset.order)return;const select=e.target,id=select.dataset.order;select.disabled=true;try{const data=await request(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify({status:select.value})});orders=orders.map(o=>o.id===id?data.order:o);render();const stats=await request('/api/admin/orders');$('#total').textContent=stats.stats.total;$('#new').textContent=stats.stats.newOrders||0;$('#completed').textContent=stats.stats.completed||0;}catch(err){$('#dashboard-error').textContent=err.message;render();}});
request('/api/admin/session').then(()=>load()).catch(err=>{if(err.message!=='Please sign in.')$('#login-error').textContent=err.message;});
