import { products } from './data.js';
const paths={bag:'<path d="M6 7h12l2 14H4L6 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',layers:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',trash:'<path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',chat:'<path d="M21 11.5a8.5 8.5 0 0 1-12.6 7.4L3 21l1.8-5.5A8.5 8.5 0 1 1 21 11.5Z"/><path d="M8 10h8M8 14h5"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
const key='cretechem-cart-v1';let cart=[];
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))cart=products.flatMap(p=>{const quantity=saved.filter(x=>x.id===p.id&&Number.isInteger(x.quantity)&&x.quantity>0).reduce((sum,x)=>sum+x.quantity,0);return quantity?[{id:p.id,quantity:Math.min(999,quantity)}]:[];});}catch{}
export function initCart(){
 if(document.querySelector('#product-cart'))return;
 let requestId=crypto.randomUUID(),lastPayload='',timer,saving=false,step='review',savedOrder=null;
 const $=s=>document.querySelector(s);
 document.querySelectorAll('[data-open-cart]').forEach(button=>{button.innerHTML=`${icon('bag')}<span class="cart-toggle-label">Cart</span><span class="cart-count" data-cart-count>0</span>`;button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-controls','product-cart');});
 document.body.insertAdjacentHTML('beforeend',`<dialog id="product-cart" class="cart-dialog" aria-labelledby="cart-title">
 <header class="cart-head"><div class="cart-heading"><span class="cart-heading-icon">${icon('bag')}</span><div><p class="cart-kicker">YOUR PROJECT, PROTECTED</p><h2 id="cart-title" tabindex="-1">Your cart</h2></div></div><button class="cart-icon-button" type="button" data-close-cart aria-label="Close cart">${icon('close')}</button></header>
 <ol class="cart-steps" aria-label="Quotation request steps"><li data-step="review" aria-current="step"><span>1</span>Review products</li><li data-step="details"><span>2</span>Your details</li></ol>
 <div class="cart-scroll">
 <section id="cart-review" aria-label="Selected products"><div class="cart-section-label"><h3>Selected products</h3><span id="cart-line-count"></span></div><div id="cart-items"></div><div class="cart-guidance">${icon('chat')}<p><strong>A solution tailored to your project.</strong>Our team will confirm the right specifications, pack sizes and pricing with you.</p></div></section>
 <section id="cart-empty" class="cart-empty" hidden><span class="cart-empty-art">${icon('bag')}<i>+</i></span><p class="cart-kicker">LET’S START YOUR PROJECT</p><h3>Protection starts here.</h3><p>Add the products you need.<br>We’ll help you find the right solution.</p><button class="cart-primary" type="button" data-browse-products>Explore products ${icon('arrow')}</button><span class="cart-empty-note">6 product families · Expert guidance</span></section>
 <section id="cart-details" hidden><button type="button" class="cart-back" data-cart-back>${icon('back')} Back to products</button><h3 class="cart-details-title">Where can we reach you?</h3><p class="cart-intro">Share a few details so our team can prepare your quotation.</p>
 <form class="checkout-form" id="checkout"><div class="checkout-fields"><label>Full name<input name="name" autocomplete="name" placeholder="Your full name" required maxlength="100"></label><label>Phone / WhatsApp<input name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="03XX XXXXXXX" required minlength="7" maxlength="25" pattern="[+0-9 ()\\-]{7,25}"></label></div><label>Delivery address / project location<textarea name="address" autocomplete="street-address" placeholder="Area, city and project location" required maxlength="600" rows="2"></textarea></label><label>Project notes <span class="cart-optional">Optional</span><textarea name="notes" placeholder="Tell us about the surface, area or pack sizes you need…" maxlength="1000" rows="3"></textarea></label><p class="form-message" id="checkout-error" role="alert"></p></form></section>
 <section id="order-success" class="cart-success" hidden aria-live="polite"><span class="cart-success-icon">${icon('check')}</span><p class="cart-kicker">REQUEST RECEIVED</p><h3>Your order is saved.</h3><p>One last step: send the prepared message on WhatsApp to speak with our team.</p><p class="cart-reference"></p><a class="cart-primary cart-whatsapp" target="_blank" rel="noopener">${icon('chat')} Open WhatsApp ${icon('arrow')}</a><button type="button" class="cart-back" data-browse-products>Continue browsing</button></section></div>
 <footer class="cart-footer"><div class="cart-summary"><div><span id="cart-total"></span><small>Quotation request</small></div><strong>Price on request</strong></div><button class="cart-primary" id="cart-next" type="button">Continue to details ${icon('arrow')}</button><button class="cart-primary cart-whatsapp" id="cart-submit" type="submit" form="checkout" hidden>${icon('chat')} Save & open WhatsApp ${icon('arrow')}</button><p id="cart-footnote">No payment now. Get a quotation from our team.</p></footer></dialog>
 <div class="cart-toast" role="status" aria-live="polite" hidden><span class="cart-toast-icon">${icon('check')}</span><span data-toast-message></span><button type="button" data-open-cart>View cart ${icon('arrow')}</button></div>`);
 const dialog=$('#product-cart');
 // HTML patterns use Unicode-set syntax, which requires escaped parentheses.
 $('#checkout [name="phone"]').pattern=String.raw`[+0-9 \(\)\-]{7,25}`;
 function render(){
  const total=cart.reduce((sum,item)=>sum+item.quantity,0);try{localStorage.setItem(key,JSON.stringify(cart));}catch{}
  document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=total);
  document.querySelectorAll('.cart-toggle').forEach(el=>el.setAttribute('aria-label',`Open cart, ${total} ${total===1?'item':'items'}`));
  $('#cart-line-count').textContent=`${cart.length} ${cart.length===1?'family':'families'}`;$('#cart-total').textContent=`${total} ${total===1?'item':'items'} selected`;
  $('#cart-items').innerHTML=cart.map(item=>{const p=products.find(p=>p.id===item.id);return `<article class="cart-item"><div class="cart-product-art" data-tone="${p.tone}">${icon('layers')}</div><div class="cart-product-info"><h3>${p.name}</h3><p>${p.use}</p><div class="cart-item-actions"><div class="quantity" role="group" aria-label="${p.name} quantity"><button type="button" data-quantity="${p.id}" data-delta="-1" aria-label="Decrease ${p.name} quantity" ${item.quantity===1?'disabled':''}>−</button><span aria-label="Quantity">${item.quantity}</span><button type="button" data-quantity="${p.id}" data-delta="1" aria-label="Increase ${p.name} quantity" ${item.quantity===999?'disabled':''}>+</button></div><button class="remove-item" type="button" data-remove="${p.id}" aria-label="Remove ${p.name}">${icon('trash')}<span>Remove</span></button></div></div></article>`;}).join('');
  const empty=cart.length===0;if(empty)step='review';
  $('#cart-review').hidden=empty||step!=='review'||!!savedOrder;$('#cart-empty').hidden=!empty||!!savedOrder;$('#cart-details').hidden=empty||step!=='details'||!!savedOrder;$('#order-success').hidden=!savedOrder;$('.cart-footer').hidden=empty||!!savedOrder;$('.cart-steps').hidden=empty||!!savedOrder;$('#cart-next').hidden=step!=='review';$('#cart-submit').hidden=step!=='details';
  $('#cart-footnote').textContent=step==='details'?'Saved to our dashboard first. Tap Send in WhatsApp to finish.':'No payment now. Get a quotation from our team.';
  dialog.querySelectorAll('[data-step]').forEach(el=>{if(el.dataset.step===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});
 }
 const focusTitle=()=>$('#cart-title').focus({preventScroll:true});
 function changeStep(next){step=next;render();$('.cart-scroll').scrollTop=0;if(next==='details')$('#checkout input').focus({preventScroll:true});else focusTitle();}
 function openCart(){render();$('.cart-toast').hidden=true;if(!dialog.open)dialog.showModal();focusTitle();}
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 $('#cart-next').addEventListener('click',()=>changeStep('details'));
 document.addEventListener('click',e=>{
  if(e.target.closest('[data-open-cart]'))openCart();if(e.target.closest('[data-close-cart]'))dialog.close();
  if(e.target.closest('[data-browse-products]')){dialog.close();if($('#products'))$('#products').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});else location.href='index.html#products';}
  if(saving)return;if(e.target.closest('[data-cart-back]'))changeStep('review');
  const add=e.target.closest('[data-add-cart]');if(add){const p=products.find(p=>p.id===add.dataset.addCart);if(!p)return;const item=cart.find(x=>x.id===p.id);if(item)item.quantity=Math.min(999,item.quantity+1);else cart.push({id:p.id,quantity:1});savedOrder=null;requestId=crypto.randomUUID();render();$('[data-toast-message]').textContent=`${p.name} added to cart`;$('.cart-toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('.cart-toast').hidden=true,4500);}
  const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==remove.dataset.remove);requestId=crypto.randomUUID();render();focusTitle();}
  const quantity=e.target.closest('[data-quantity]');if(quantity){const item=cart.find(x=>x.id===quantity.dataset.quantity);if(!item)return;item.quantity=Math.max(1,Math.min(999,item.quantity+Number(quantity.dataset.delta)));requestId=crypto.randomUUID();render();const control=dialog.querySelector(`[data-quantity="${item.id}"][data-delta="${quantity.dataset.delta}"]`);if(!control.disabled)control.focus({preventScroll:true});else focusTitle();}
 });
 $('#checkout').addEventListener('submit',async e=>{
  e.preventDefault();if(saving||!cart.length)return;const form=e.currentTarget,button=$('#cart-submit'),error=$('#checkout-error'),customer=Object.fromEntries(new FormData(form)),items=cart.map(x=>({...x}));
  const payload=JSON.stringify({customer,items});if(lastPayload&&lastPayload!==payload)requestId=crypto.randomUUID();lastPayload=payload;saving=true;button.disabled=true;button.innerHTML='<span class="cart-spinner" aria-hidden="true"></span> Saving your order…';error.textContent='';form.querySelectorAll('input,textarea').forEach(el=>el.readOnly=true);
  try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,customer,items})});let result;try{result=await response.json();}catch{throw new Error('The order service is temporarily unavailable. Your cart has been kept. Please try again shortly.');}if(!response.ok)throw new Error(result.error||'Could not save your order. Please try again.');savedOrder=result.order;cart=[];form.reset();render();$('.cart-reference').textContent=`Reference: ${result.order.id}`;$('#order-success a').href=result.whatsappUrl;$('.cart-scroll').scrollTop=0;focusTitle();window.open(result.whatsappUrl,'_blank','noopener');requestId=crypto.randomUUID();lastPayload='';
  }catch(err){error.textContent=err.message||'Connection failed. Your cart has been kept.';error.scrollIntoView({block:'nearest'});}finally{saving=false;button.disabled=false;button.innerHTML=`${icon('chat')} Save & open WhatsApp ${icon('arrow')}`;form.querySelectorAll('input,textarea').forEach(el=>el.readOnly=false);}
 });render();
}
